#!/usr/bin/env bash
#
# Script name: dm-colpick
# Description: Copy a color to your clipboard using rofi, change the colors if needed
# Dependencies: rofi, wl-copy (for Wayland), xclip (for X11)

# Set with the flags "-e", "-o pipefail" cause the script to fail
# if certain things happen, which is a good thing. Otherwise, we can
# get hidden bugs that are hard to discover.
set -euo pipefail

declare -A colpick_list
colpick_list[black]="#282a36"
colpick_list[red]="#ff5555"
colpick_list[green]="#5af78e"
colpick_list[yellow]="#f1fa8c"
colpick_list[blue]="#57c7ff"
colpick_list[magenta]="#ff6ac1"
colpick_list[cyan]="#8be9fd"
colpick_list[white]="#f1f1f0"
colpick_list[orange]="#ffb86c"
colpick_list[purple]="#bd9cf9"

cp2cb() {
  case "$XDG_SESSION_TYPE" in
    'wayland') wl-copy ;;
    'x11') xclip -selection clipboard ;;
    *) echo "Error: Unknown display server" >&2; exit 1 ;;
  esac
}

main() {
  # Show color options using rofi
  selected="$(printf '%s\n' "${!colpick_list[@]}" | rofi -dmenu -l 10 -theme ~/.config/rofi/dt-center.rasi -i -p "color:" "$@")"
  
  # Exit if no selection was made
  [ -z "${selected}" ] && exit 1
  
  # Copy the selected color to clipboard
  echo -n "${colpick_list["${selected}"]}" | cp2cb
}

[[ "${BASH_SOURCE[0]}" == "${0}" ]] && main "$@"
