#!/usr/bin/env bash

set -euo pipefail

# WORD="$(rofi -dmenu -i -p "Search:")"
WORD="$(echo 'Search any Word' | rofi -dmenu -theme ~/.config/rofi/dt-center.rasi -i -p 'Search:')"
TESTWORD="$(dym -c -n=1 "$WORD")"

if [ "$WORD" != "$TESTWORD" ]; then
	KEYWORD=$(dym -c "$WORD" | rofi -dmenu -theme ~/.config/rofi/dt-center.rasi -i -l 10 -p "was $WORD a misspelling?(select/no)")
	if [ "$KEYWORD" = "no" ] || [ "$KEYWORD" = "n" ]; then
		KEYWORD="$WORD"
	fi
else
	KEYWORD="$WORD"
fi

if ! [ "${KEYWORD}" ]; then
	printf 'No word inserted\n' >&2
	exit 0
fi
kitty -e trans -v -d "$WORD"

# repeat this process until choise is no

while true; do
  CHOICE=$(echo -e "no\nyes" | rofi -dmenu -theme ~/.config/rofi/dt-center.rasi -l 10 -i -p "Do you want to search another word?")
  if [ "$CHOICE" = "yes" ]; then
    WORD="$(echo 'Search any Word' | rofi -dmenu -theme ~/.config/rofi/dt-center.rasi -i -p 'Search:')"
    TESTWORD="$(dym -c -n=1 "$WORD")"
    if [ "$WORD" != "$TESTWORD" ]; then
      KEYWORD=$(dym -c "$WORD" | rofi -dmenu -theme ~/.config/rofi/dt-center.rasi -i -l 10 -p "was $WORD a misspelling?(select/no)")
      if [ "$KEYWORD" = "no" ] || [ "$KEYWORD" = "n" ]; then
        KEYWORD="$WORD"
      fi
    else
      KEYWORD="$WORD"
    fi
    if ! [ "${KEYWORD}" ]; then
      printf 'No word inserted\n' >&2
      exit 0
    fi
    kitty -e trans -v -d "$WORD"
  else
    exit 1
  fi
done
