#!/bin/sh

TERMINAL="kitty"  # or "alacritty", "wezterm", etc.
LOCATION="${LOCATION:-hyderabad}"
weatherreport="$HOME/.local/share/weatherreport"

getforecast() {
    curl -sf "wttr.in/$LOCATION" > "$weatherreport" || exit 1
}

# Extract precipitation, low, and high
showweather() {
    rain=$(sed '16q;d' "$weatherreport" |
        grep -wo "[0-9]*%" | sort -rn | sed "s/^/🌧️/g;1q" | tr -d '\n')

    temps=$(sed '13q;d' "$weatherreport" |
        grep -o "m\\([-+]\\)*[0-9]\\+" | sed 's/+//g' |
        sort -n -t 'm' -k 2n | sed -e 1b -e '$!d' | tr '\n|m' ' ' |
        awk '{print " ❄️" $1 "° 🌞" $2 "°"}')

    echo "$rain$temps"
}

# Update forecast once daily
[ "$(stat -c %y "$weatherreport" 2>/dev/null | cut -d' ' -f1)" = "$(date '+%Y-%m-%d')" ] || getforecast

# Output for Waybar
echo "{\"text\": \"$(showweather)\", \"tooltip\": \"Click to refresh or view full forecast\"}"
