#!/usr/bin/env bash

# USE: rofi -show find -modi find:~/.config/scripts/rofifinder

# Directories to search
SEARCH_DIRS=("$HOME" "/mnt/Karna/" ) 

if [ ! -z "$@" ]; then
  QUERY=$@
  if [[ "$@" == /* ]]; then
    if [[ "$@" == *\?\? ]]; then
      coproc ( exo-open "${QUERY%\/* \?\?}" > /dev/null 2>&1 )
      exec 1>&-
      exit
    else
      coproc ( exo-open "$@" > /dev/null 2>&1 )
      exec 1>&-
      exit
    fi
  elif [[ "$@" == \!\!* ]]; then
    echo "!!-- Type your search query to find files"
    echo "!!-- To search again type !<search_query>"
    echo "!!-- To search parent directories type ?<search_query>"
    echo "!!-- You can print this help by typing !!"
  elif [[ "$@" == \?* ]]; then
    echo "!!-- Type another search query"
    for dir in "${SEARCH_DIRS[@]}"; do
      while read -r line; do
        echo "$line" \?\?
      done <<< "$(find "$dir" -type d -path '*/\.*' -prune -o -not -name '.*' -type f -iname "*${QUERY#\?}*" -print)"
    done
  else
    echo "!!-- Type another search query"
    for dir in "${SEARCH_DIRS[@]}"; do
      find "$dir" -type d -path '*/\.*' -prune -o -not -name '.*' -type f -iname "*${QUERY#!}*" -print
    done
  fi
else
  echo "!!-- Type your search query to find files"
  echo "!!-- To search again type !<search_query>"
  echo "!!-- To search parent directories type ?<search_query>"
  echo "!!-- You can print this help by typing !!"
fi
