#!/bin/sh

# Prints the current volume or 🔇 if muted.

case $BLOCK_BUTTON in
#	1) setsid -f "$TERMINAL" -e pulsemixer ;;

	1) pamixer -t ;;
	2) pavucontrol ;;
	4) pamixer --allow-boost -i 5 ;;
	5) pamixer --allow-boost -d 5 ;;
	3) notify-send "📢 Volume module" "\- Shows volume 🔊, 🔇 if muted.
- Middle click to open PavuControl.
- Scroll to change." ;;
esac

[ $(pamixer --get-mute) = true ] && echo "🔇 M" && exit

vol="$(pamixer --get-volume)"

if [ "$vol" -gt "60" ]; then
	icon="🔊"
elif [ "$vol" -lt "20" ]; then
	icon="🔈"
else
	icon="🔉"
fi

echo "$icon $vol%"
