#!/usr/bin/env bash

# Prints all batteries, their percentage remaining and an emoji corresponding
# to charge status (🔌 for plugged up, 🔋 for discharging on battery, etc.).

# find the backlight directory (handle multiple possibilities)
backlight_dir=$(ls /sys/class/backlight/ | head -n 1)

# current brightness and max brightness
curr_brightness=$(cat /sys/class/backlight/$backlight_dir/brightness)
max_brightness=$(cat /sys/class/backlight/$backlight_dir/max_brightness)

brightness_per=$((100 * curr_brightness / max_brightness))

case $BLOCK_BUTTON in
	3) dunstify -u low -i /usr/share/icons/dunst/leaf.png "🔋 Battery Moldule" "
💡: Brightness: $((brightness_per))% 
🔋: discharging
🛑: not charging
♻: stagnant charge
🔌: charging
⚡: charged
❗: battery very low!" ;;
	6) setsid -f "st" -e "nvim" "$0" ;;
esac

# Loop through all attached batteries and format the info
for battery in /sys/class/power_supply/BAT?*; do
	# If non-first battery, print a space separator.
	[ -n "${capacity+x}" ] && printf " "
	# Sets up the status and capacity
	case "$(cat "$battery/status" 2>&1)" in
		"Full") status="⚡" ;;
		"Discharging") status="🔋" ;;
		"Charging") status="🔌" ;;
		"Not charging") status="🛑" ;;
		"Unknown") status="♻️" ;;
		*) exit 1 ;;
	esac
	capacity="$(cat "$battery/capacity" 2>&1)"
	# Will make a warn variable if discharging and low
	[ "$status" = "🔋" ] && [ "$capacity" -le 25 ] && warn="❗"
	# Prints the info
	printf "%s%s%d%%" "$status" "$warn" "$capacity"; unset warn
done && printf "\\n"

