#!/bin/sh

# Get current hour (12-hour format)
clock=$(date '+%I')

# Map hour to clock emoji
case "$clock" in
	"01") icon="🕐" ;;
	"02") icon="🕑" ;;
	"03") icon="🕒" ;;
	"04") icon="🕓" ;;
	"05") icon="🕔" ;;
	"06") icon="🕕" ;;
	"07") icon="🕖" ;;
	"08") icon="🕗" ;;
	"09") icon="🕘" ;;
	"10") icon="🕙" ;;
	"11") icon="🕚" ;;
	"12") icon="🕛" ;;
esac

# Handle mouse clicks
case $BLOCK_BUTTON in
	2)
		today=$(date +%-d)  # No leading zero
		cal_output=$(cal)

		# Highlight today's date using awk and HTML bold tags
		highlighted=$(echo "$cal_output" | awk -v today="$today" '{
			for (i = 1; i <= NF; i++) {
				if ($i == today) {
					$i = "<b>" $i "</b>"
				}
			}
			print
		}')

		notify-send -u low -i none -h string:markup:html "This Month" "$highlighted"
		;;
	6)
		"$TERMINAL" -e "$EDITOR" "$0"
		;;
esac

# Final date output
date "+ %d %b %Y(%a) $icon %I:%M:%S %p"

