#!/bin/bash

cover_path="$HOME/.config/i3blocks/scripts/music.png"

# Handle click to go to the previous track
case $BLOCK_BUTTON in
	1) 
    mpc prev | " ";
    # mpc prev | "⏮️";
    dunstify -u low --replace=69 -i "$cover_path" "$(mpc current)";
    ;;  
  2) 
    mpc repeat | " "; 
    rand=$(mpc | sed -n '3p' | awk '{print $3}');
    dunstify -u low --replace=69 -i /usr/share/icons/dunst/music.png "Toggle Repeat" "Repeat Mode => $rand";
    ;;
  3) 
    mpc single | " "; 
    single=$(mpc | sed -n '3p' | awk '{print $7}');
    dunstify -u low --replace=69 -i /usr/share/icons/dunst/music.png "Toggle Single" "Single Repeat Mode => $single";
    ;;
esac

echo " " 
