#!/bin/bash

cover_path="$HOME/.config/i3blocks/scripts/music.png"

# Handle click to go to the next track
case $BLOCK_BUTTON in
  1) mpc next | "⏭️";
     dunstify -u low --replace=69 -i "$cover_path" "$(mpc current)";
    ;;  
esac

echo "⏭️"
