#!/bin/bash

cover_path="$HOME/.config/i3blocks/scripts/music.png"

# Get the current MPD status
status=$(mpc status | grep -Eo '\[playing\]|\[paused\]')
song=$(mpc current)

# Handle click event
case $BLOCK_BUTTON in
    1)if [ "$status" == "[playing]" ]; then
        # mpc pause | "⏸️";
        mpc pause | "";
        dunstify -u low --replace=69 -i "$cover_path" "Paused" "$(mpc current)";
      else
        mpc play | ""; 
        # mpc play | "▶️"; 
        dunstify -u low --replace=69 -i "$cover_path" "$(mpc current)";
      fi
      ;;
    2) setsid -f "st" -T ncmpcpp-f -e "$HOME/.ncmpcpp/scripts/ncmpcpp-art" ;; 
    3) 
      mpc stop | ""; 
      # mpc stop | "⏹️"; 
      dunstify -u low --replace=69 -i "$cover_path" "Stopped" "No song playing";;
esac

status=$(mpc status | grep -Eo '\[playing\]|\[paused\]')

stop_icon_nerd_font=

# Display Play or Pause icon based on status
if [ "$status" == "[playing]" ]; then
    echo ""  
elif [ "$status" == "[paused]" ]; then
    echo ""  # Play icon when paused
else
    echo ""  # Stop icon when stopped
fi

