#!/bin/sh

case $BUTTON in
	1) notify-send "🧠 Memory hogs" "$(ps axch -o cmd,%mem | awk '{cmd[$1]+=$2} END {for (i in cmd) print i, cmd[i]}' | sort -nrk2 | head)" ;;
	2) setsid -f "st" -e btop ;;
	3) notify-send "🧠 Memory module" "\- Shows Memory Used.
- Click to show memory hogs.
- Middle click to open btop." ;;
	8) setsid -f "st" -e "nvim" "$0" ;;
esac

free --mebi | sed -n '2{p;q}' | awk '{printf ("🧠 %2.2fG\n", ( $3 / 1024), ($2 / 1024))}'
# free --mebi | sed -n '2{p;q}' | awk '{printf ("🧠 %2.2fGiB/%2.2fGiB\n", ( $3 / 1024), ($2 / 1024))}'
