#!/bin/sh

# Define a list of choices and their corresponding commands
declare -A apps=(
    ["Open Chess - Chess Nativefier"]="$HOME/apps/chess-linux-x64/chess"
    ["Edit TODOS"]="kitty -e nvim $HOME/.config/conky/todo.md"
)

# Generate the menu dynamically
choice=$(printf "%s\n" "${!apps[@]}" | rofi -dmenu -p "Select Application:" -theme $HOME/.config/rofi/dt-center.rasi)

# Run the chosen application if it exists
if [[ -n "$choice" && -n "${apps[$choice]}" ]]; then
    eval "${apps[$choice]}"
else
    echo "Invalid choice or application not found."
fi

