#!/bin/sh

# searchstr="meet.google.com is sharing your screen"
searchstr="Zen — Sharing Indicator"
while [ ! -z $(xdotool search --name "$searchstr" getwindowpid) ]
do
	sleep 30s
	pkill -RTMIN+19 i3blocks
done
