#!/usr/bin/env bash

while true; do
    # Running ps to get running processes and display in dmenu.
    selected="$(ps --user "$USER" -F | \
                dmenu -i -l 10 -p "Search for process to kill:" "$@" | \
                awk '{print $2" "$11}')"

    # Nested 'if' statements. The outer 'if' statement is what to do
    # when we select one of the 'selected' options listed in dmenu.
    if [[ -n $selected ]]; then
        # Piping No/Yes into dmenu as a safety measure.
        answer="$(echo -e "No\nYes" | dmenu -i -l 5 -p "Kill $selected?" "$@")"

        if [[ $answer == "Yes" ]]; then
            # Kill the process.
            kill -9 "${selected%% *}"
            echo "Process $selected has been killed."

            # Ask if the user wants to kill another process.
            another="$(echo -e "No\nYes" | dmenu -i -l 5 -p "Kill another process?" "$@")"
            if [[ $another == "No" ]]; then
                echo "Program terminated." && exit 0
            fi
        else
            echo "Program terminated." && exit 1
        fi
    else
        echo "No process selected." && exit 1
    fi
done
