#!/bin/bash

# Function to set a property to "on"
set_property_on() {
    device="$1"
    property="$2"
    xinput set-prop "$device" "$property" 1
    echo "$property enabled"
}

# Set natural scrolling to "on"
set_property_on "DLL09D9:00 04F3:3147 Touchpad" "libinput Natural Scrolling Enabled"

# Set tapping to "on"
set_property_on "DLL09D9:00 04F3:3147 Touchpad" "libinput Tapping Enabled"

