#!/bin/bash
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
UNICODE=`cat "$DIR"/unicode-list.txt | dmenu -i -l 10 -p "" | cut -d\' -f2 | tail -c +4 | head -c -2`
printf '\u'$UNICODE | xclip -selection c
icon=`printf '\u'$UNICODE`
notify-send -t 2000 "$icon copied!"
