#!/bin/bash

# invidious_instance="https://vid.puffyan.us" ytfzf --rii -D

# Define the options
options=("Watch Videos" "Open Subscriptions" "Open History" "Download Videos" "Download Subscriptions")

# Prompt the user to select an option using dmenu
chosen_option=$(printf '%s\n' "${options[@]}" | dmenu -i -l 10 -p "Choose an option:")

# Execute commands based on the chosen option
case $chosen_option in
"Watch Videos")
	choice=$(printf "Relevent\nDate\nRating\nViews" | dmenu -i -l 10 -p "Sort by:")
	case $choice in
	"Relevent")
		invidious_instance="https://vid.puffyan.us" ytfzf --rii -fD --sort-by=relevance
		;;
	"Date")
		invidious_instance="https://vid.puffyan.us" ytfzf --rii -fD --sort-by=upload_date
		;;
	"Rating")
		invidious_instance="https://vid.puffyan.us" ytfzf --rii -fD --sort-by=rating
		;;
	"Views")
		invidious_instance="https://vid.puffyan.us" ytfzf --rii -fD --sort-by=view_count
		;;
	*)
		# If an invalid option is chosen
		echo "Invalid option. Exiting..."
		exit 1
		;;
	esac
	;;
"Open Subscriptions")
	# Command for Option 2
	invidious_instance="https://vid.puffyan.us" ytfzf --rii -fcS --fancy-subs -D
	;;
"Open History")
	# Command for Option 3
	invidious_instance="https://vid.puffyan.us" ytfzf --rii -H -D
	;;
"Download Videos")
	# Command for Option 4
	choice=$(printf "Relevent\nDate\nRating\nViews" | dmenu -i -l 10 -p "Sort by:")
	case $choice in
	"Relevent")
		cd ~/Downloads && invidious_instance="https://vid.puffyan.us" ytfzf --rii -fd -D --sort-by=relevance
		;;
	"Date")
		cd ~/Downloads && invidious_instance="https://vid.puffyan.us" ytfzf --rii -fd -D --sort-by=upload_date
		;;
	"Rating")
		cd ~/Downloads && invidious_instance="https://vid.puffyan.us" ytfzf --rii -fd -D --sort-by=rating
		;;
	"Views")
		cd ~/Downloads && invidious_instance="https://vid.puffyan.us" ytfzf --rii -fd -D --sort-by=view_count
		;;
	*)
		# If an invalid option is chosen
		echo "Invalid option. Exiting..."
		exit 1
		;;
	esac

	choice=$(printf "Open Folder\nPlay Video\nExit" | dmenu -i -l 10 -p "Choose an option:")
	if [ "$choice" = "Open Folder" ]; then
		st -e ranger ~/Downloads
		dunstify "Download Completed from Subscriptions & Opened in Ranger"
	elif [ "$choice" = "Play Video" ]; then
		video_name=$(find ~/Downloads -type f -name "*.mkv" -printf "%T@ %p\n" | sort -n | tail -1 | cut -f2- -d" ")
		dunstify "Download Completed from Subscriptions & Playing Video..."
		# Play the video
		mpv ~/Downloads/"$video_name"
	else
		dunstify "Exiting..."
		exit 0
	fi
	;;
"Download Subscriptions")
	# Command for Option 5
	cd ~/Downloads && invidious_instance="https://vid.puffyan.us" ytfzf --rii -fcS --fancy-subs -d -D
	choice=$(printf "Open Folder\nPlay Video\nExit" | dmenu -i -l 10 -p "Choose an option:")
	if [ "$choice" = "Open Folder" ]; then
		st -e ranger ~/Downloads
		dunstify "Download Completed from Subscriptions & Opened in Ranger"
	elif [ "$choice" = "Play Video" ]; then
		video_name=$(find ~/Downloads -type f -name "*.mkv" -printf "%T@ %p\n" | sort -n | tail -1 | cut -f2- -d" ")
		dunstify "Download Completed from Subscriptions & Playing Video..."
		# Play the video
		mpv ~/Downloads/"$video_name"
	else
		dunstify "Exiting..."
		exit 0
	fi

	;;
*)
	# If an invalid option is chosen
	echo "Invalid option. Exiting..."
	exit 1
	;;
esac

exit 0
