#!/bin/bash

# Define global ROFI command with default options
ROFI="rofi -dmenu -theme ~/.config/rofi/dt-center.rasi -i"

# Directory containing wallpapers
WALL="$HOME/dotfiles/hypr_wall"
dir=$(find $WALL -mindepth 1 -maxdepth 1 -type d -exec basename {} \;)
choice=$(echo -e "Random\n$dir\nDownload to Collection\nTemporary Wallpaper\nQuit" | $ROFI -p "Choose an Option:")

WALLPAPER_DIR="$WALL/$choice"

# Random transition type generator function
get_random_transition() {
  echo "fade wipe left right top bottom center random" | tr ' ' '\n' | shuf -n 1
}

if [ "$choice" = "Random" ]; then
	wall_dir=$(ls $WALL)
	wall=""

	for dir in $wall_dir; do
		wall+=$(find $WALL/$dir -type f -name "*.jpg" -o -name "*.png")
	done

	valid_paper="No"
	until [ "$valid_paper" = "Yes" ]; do
		wallk=$(echo $wall | tr " " "\n" | shuf -n 1)
		echo $wallk
		# Apply the wallpaper with a random transition effect
		transition=$(get_random_transition)
		swww img --transition-type "$transition" "$wallk"
		valid_paper="$(printf "Yes\nNo" | $ROFI -p "Do you like the new wallpaper?")"
	done
	exit 1
fi

if [ "$choice" = "Download to Collection" ]; then
	/usr/local/bin/waldl
	if [ ! -d "$WALL/Wallheaven" ]; then
		mkdir "$WALL/Wallheaven"
	fi
	WALLPAPER_DIR="$WALL/Wallheaven"
fi

if [ "$choice" = "Temporary Wallpaper" ]; then
	if [ ! -d "$HOME/.cache/wallheaven" ]; then
		mkdir $HOME/.cache/wallheaven
	fi
	/usr/local/bin/waldl -d $HOME/.cache/wallheaven

	if [ -z "$(ls -A $HOME/.cache/wallheaven)" ]; then
		dunstify "Directory is empty."
		exit 1
	fi
	choice=$(echo -e "Yes\nNo" | $ROFI -p "Would you like to change wallpaper?")
	if [ "$choice" = "No" ]; then
		dunstify "Program terminated."
		exit 1
	fi
	wall=$(ls -t $HOME/.cache/wallheaven | head -n 1)
	wall="$HOME/.cache/wallheaven/$wall"
	dunstify "Wallpaper set to $wall"
	if [ -n "$wall" ]; then
		# Apply the wallpaper with a random transition effect
		transition=$(get_random_transition)
		swww img --transition-type "$transition" "$wall"
	else
		dunstify "No wallpaper selected."
	fi
	exit 1
fi

if [ "$choice" = "Quit" ]; then
	dunstify "Program terminated."
	exit 1
fi

# if the directory is empty, and its path should not be .cache/wallheaven then download some WALLPAPERS
if [ "$WALLPAPER_DIR" != "$HOME/.cache/wallheaven" ]; then
	if [ -z "$(ls -A $WALLPAPER_DIR)" ]; then
		dunstify "Directory is empty."
		choice=$(echo -e "Download\nExit" | $ROFI -p "Would you like to Download Some?")
		if [ "$choice" = "Download" ]; then
			/usr/local/bin/waldl
		else
			dunstify "Program terminated."
			exit 1
		fi
	fi
fi

# List wallpapers in the directory
WALLPAPERS=$(ls "$WALLPAPER_DIR")

if [ -z "$WALLPAPERS" ]; then
	dunstify "No wallpapers found."
	exit 1
fi

# Prompt user to choose action
ACTION=$(echo -e "Choose\nRandom\nExit" | $ROFI -p "What would you like to do?")

case $ACTION in
"Choose")
	SELECTED_WALLPAPER=$(sxiv -to $WALLPAPER_DIR | awk '{print $NF}')
	# Check if a wallpaper was selected
	if [ -n "$SELECTED_WALLPAPER" ]; then
		# Apply the wallpaper with a random transition effect
		transition=$(get_random_transition)
		swww img --transition-type "$transition" "$SELECTED_WALLPAPER"
	else
		dunstify "No wallpaper selected."
	fi
	;;

"Random")
	valid_paper="No"
	until [ "$valid_paper" = "Yes" ]; do
		RANDOM_WALLPAPER=$(ls "$WALLPAPER_DIR" | shuf -n 1)
		# Apply the wallpaper with a random transition effect
		transition=$(get_random_transition)
		swww img --transition-type "$transition" "$WALLPAPER_DIR/$RANDOM_WALLPAPER"
		valid_paper="$(printf "Yes\nNo" | $ROFI -p "Do you like the new wallpaper?")"
	done
	;;

"Exit") dunstify "Program terminated" && exit 1 ;;
*)
	dunstify "Invalid option."
	;;
esac
