#!/bin/bash

# Take URL input using dmenu
url=$(echo "URL" | dmenu -p "Enter YouTube channel:")

# Check if url is empty
if [ -z "$url" ]; then
	dunstify "No URL entered. Exiting."
	exit 1
fi

# # Define the Python script
# python_script=$(
# 	cat <<EOF
# import sys
# import requests
# from bs4 import BeautifulSoup
#
# def extract_channel_id(url):
#     try:
#         response = requests.get(url)
#         if response.status_code == 200:
#             soup = BeautifulSoup(response.content, "html.parser")
#             channel_link = soup.find("link", itemprop="url")
#             if channel_link:
#                 return channel_link["href"].split("/")[-1]
#             else:
#                 return "Channel ID not found. Make sure the provided URL is a YouTube channel URL."
#         else:
#             return "Failed to fetch URL. Status code:", response.status_code
#     except Exception as e:
#         return "An error occurred:", str(e)
#
# if __name__ == "__main__":
#     if len(sys.argv) != 2:
#         print("Usage: python get_channel_id.py <youtube_channel_url>")
#         sys.exit(1)
#
#     url = sys.argv[1]
#     channel_id = extract_channel_id(url)
#     print(channel_id)
# EOF
# )
#
# Get channel ID using embedded Python script
# channel_id=$(python3 -c "$python_script" "$url")
channel_id=$(ytfzf --channel-link="$url")

# now take the last part of the url
channel_id=$(echo "$channel_id" | awk -F'/' '{print $NF}')

# Copy channel ID to clipboard
echo "$channel_id" | xclip
echo "$channel_id" | xclip -selection clipboard

# Notify user
notify-send "YouTube Channel ID" "Channel ID '$channel_id' copied to clipboard."
