[pyprland]
plugins = [
    "scratchpads",
]

[scratchpads.music]
command = "kitty --class Music -e rmpc"
# command = "alacritty --class Music -e ncmpcpp -c ~/.ncmpcpp/config-art"
class = "Music"
position = "431px 175px"
size = "1100px 700px"
animate = ""
lazy = true
unfocus = "hide"
margin = 50

# [scratchpads.clipse]
# command = "kitty --class clipse -e clipse"
# class = "clipse"
# position = "621px 167px"
# size = "700px 700px"
# animate = ""
# margin = 50

[scratchpads.calc]
command = "qalculate-gtk"
class = "qalculate-gtk"
position = "431px 175px"
size = "1100px 700px"
animate = ""
lazy = true
margin = 50

[scratchpads.news]
animation = ""
command = "kitty --class news -e newsboat"
class = "news"
lazy = true
position = "431px 175px"
size = "1100px 700px"
animate = ""
margin = 50

[scratchpads.term]
animation = ""
command = "foot --title foot-dropterm --app-id foot-dropterm"
class = "foot-dropterm"
size = "60% 60%"
max_size = "1920px 100%"
lazy = true
margin = 50

[scratchpads.chess]
animation = ""
command = "$HOME/apps/Chess-linux-x64/Chess"
class = "chess-nativefier-b30d50"
size = "80% 80%"
lazy = true
position = "181px 97px"
max_size = "1920px 100%"
margin = 50
