#!/bin/bash

# Get the current MPD status (playing, paused, or stopped)
status=$(mpc status | grep -Eo '\[playing\]|\[paused\]')
song=$(mpc current)
cover_path="$HOME/.config/i3/scripts/music.png"

# Determine if the status is stopped
if [ -z "$status" ]; then
    status="stopped"
fi

# Set notification message based on the status
if [ "$status" == "[playing]" ]; then
   dunstify -u low --replace=69 -i "$cover_path" "$(mpc current)" 
elif [ "$status" == "[paused]" ]; then
    dunstify -u low --replace=69 -i "$cover_path" "Paused" "$(mpc current)" 
else
    dunstify -u low --replace=69 -i "$cover_path" "Stopped" "No song playing"
fi
