#!/usr/bin/env bash

set_property() {
    device="$1"
    property="$2"
    shift 2
    xinput set-prop "$device" "$property" "$@"
    echo "$property set to $*"
}

# Touchpad settings
set_property "DLL09D9:00 04F3:3147 Touchpad" "libinput Natural Scrolling Enabled" 1
set_property "DLL09D9:00 04F3:3147 Touchpad" "libinput Tapping Enabled" 1

# Mouse settings
set_property "pointer:Razer Razer DeathAdder Essential" "libinput Accel Speed" -0.7
set_property "pointer:Razer Razer DeathAdder Essential" "libinput Accel Profile Enabled" 1 0

