#!/bin/bash

wall_dir=$(ls $HOME/Pictures/pix/)
wall=""

# now search recursively in all the dirs in wall_dir 
# for dir in $wall_dir; do 
#   wall+=$(find $HOME/Pictures/pix/$dir -type f -name "*.jpg" -o -name "*.png")
# done

wall+=$(find $HOME/Pictures/pix/ -type f -name "*.jpg" -o -name "*.png")

# now select a random wallpaper from the list
wall=$(echo $wall | tr " " "\n" | shuf -n 1)

echo "$wall"

xwallpaper --zoom $wall

rm -rf ~/.walcache/
mkdir ~/.walcache
cp $wall ~/.walcache/1
dunstify -u low -i /usr/share/icons/dunst/themes.png "Wallpaper and Theme changed"
betterlockscreen -u ~/.walcache/1
